export const APP_METADATA = {
  NAME: "PROJECT SETU Backend REST API",
  VERSION: "1.0.0",
  DESCRIPTION: "AI-Powered Government Services & Grievance Management Platform",
  AUTHOR: "PROJECT SETU Engineering Team",
} as const;

export const USER_ROLES = {
  CITIZEN: "CITIZEN",
  OFFICER: "OFFICER",
  SENIOR_OFFICER: "SENIOR_OFFICER",
  ADMIN: "ADMIN",
} as const;

export const GRIEVANCE_STATUS = {
  SUBMITTED: "SUBMITTED",
  AI_TRIAGED: "AI_TRIAGED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  UNDER_INSPECTION: "UNDER_INSPECTION",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
  ESCALATED: "ESCALATED",
  REOPENED: "REOPENED",
} as const;

export const PRIORITY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export const APPLICATION_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  DOCUMENT_VERIFICATION: "DOCUMENT_VERIFICATION",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
} as const;

export const SLA_HOURS_BASELINE = {
  CRITICAL: 6,
  HIGH: 24,
  MEDIUM: 48,
  LOW: 72,
} as const;

export const ESCALATION_LEVELS = {
  LEVEL_1_SUPERVISOR: "LEVEL_1_SUPERVISOR",
  LEVEL_2_HOD: "LEVEL_2_HOD",
  LEVEL_3_DISTRICT_MAGISTRATE: "LEVEL_3_DISTRICT_MAGISTRATE",
} as const;
